package presentation

import (
	"context"
	"fmt"
	"log"

	"connectrpc.com/connect"

	greetv1 "example/gen/greet/v1" // generated by protoc-gen-go
	"example/gen/greet/v1/greetv1connect"
)

type greetServiceHandler struct{}

func NewGreetServiceHandler() greetv1connect.GreetServiceHandler {
	return &greetServiceHandler{}
}

func (s *greetServiceHandler) Greet(
	ctx context.Context,
	req *connect.Request[greetv1.GreetRequest],
) (*connect.Response[greetv1.GreetResponse], error) {
	log.Println("Request headers: ", req.Header())
	res := connect.NewResponse(&greetv1.GreetResponse{
		Greeting: fmt.Sprintf("Hello, %s!", req.Msg.Name),
	})
	res.Header().Set("Greet-Version", "v1")
	return res, nil
}
